# Generated by Django 4.0.2 on 2022-03-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkTempValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.PositiveBigIntegerField(unique=True, verbose_name='ВК ID')),
                ('last_q_time', models.DateTimeField(auto_now=True, verbose_name='Время запроса')),
                ('code', models.CharField(max_length=8, verbose_name='reg_code')),
                ('captcha', models.CharField(default='', max_length=20, verbose_name='Ввод капчи')),
            ],
        ),
    ]
