# Generated by Django 4.0.2 on 2022-03-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_add', to=settings.AUTH_USER_MODEL, verbose_name='Кто предложил'),
        ),
        migrations.AddField(
            model_name='doc',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='docs.doc', verbose_name='Оригинал'),
        ),
        migrations.AddField(
            model_name='doc',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='doc',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='docs.doc', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='doc',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='docs.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='doc',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='docs.docfoldertype', verbose_name='Тип'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['subject', 'type'], name='docs_offer_subject_1c0858_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['is_folder'], name='docs_doc_is_fold_442608_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['subject', 'type'], name='docs_doc_subject_6e470c_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['parent'], name='docs_doc_parent__f96158_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['id'], name='docs_doc_id_44f717_idx'),
        ),
    ]
