# Generated by Django 4.0.2 on 2022-03-13 19:05

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='vk_doc_access_key',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vk_doc_id',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vk_owner_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='conv_mes_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='ID Сообщение'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='original',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_folder': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='docs.doc', verbose_name='Оригинал'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='parent',
            field=mptt.fields.TreeForeignKey(limit_choices_to={'is_folder': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='docs.doc', verbose_name='Родитель'),
        ),
    ]
