# Generated by Django 4.0.2 on 2022-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_offer_vk_doc_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfoldertype',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='docfoldertype',
            name='title_plural',
            field=models.CharField(blank=True, max_length=40, verbose_name='Мн. Название'),
        ),
    ]
