# Generated by Django 4.0.2 on 2022-03-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_offer_index_in_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfoldertype',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='Для документа'),
        ),
        migrations.AlterField(
            model_name='docfoldertype',
            name='title_plural',
            field=models.CharField(blank=True, max_length=40, verbose_name='Для папки'),
        ),
    ]
