# Generated by Django 4.0.2 on 2022-03-14 22:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_alter_docfoldertype_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='folder',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='docs.doc', verbose_name='Папка'),
        ),
    ]
