# Generated by Django 4.0.2 on 2022-03-14 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vktempvalue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caches', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
